### ISSUE TITLE
Date in exif

### ISSUE THREAD

**Issue by korjavin** [tommybutler/exifsort#3]
Could you recommend me, how to set the date of mp4 file?

**Comment by tommybutler** [comment]
I'm sorry, the metadata around video files, MPEG in particular, is out of the scope of this utility. This utility is strictly for dealing with photos. I could do some research, but currently I am unaware of how to parse the metadata from mpeg-4 or any other type of video files. I'm sure it's not impossible, since there are open source tools that already do this...

**Comment by korjavin** [comment]
Thank you tommy! And nice camel btw :)
